import * as fs from "fs";
import { AtokRomajiSettingGenerator } from "./atokRomajiSettingGenerator";

test("Input/output matching test using macOS sample", () => {
    const inputData = fs.readFileSync("./sample/sample_macos.txt", "ascii");
    const buffer = Buffer.from(inputData, "base64");

    const generator = new AtokRomajiSettingGenerator();
    generator.parseMacos(buffer);
    const result = generator.generateMacos().toString("base64");

    expect(result).toEqual(inputData);

    // console.log(generator.toString());
});

test("Input/output matching test using Windows sample", () => {
    const inputData = fs.readFileSync("./sample/sample_windows.txt", "ascii");
    const buffer = Buffer.from(inputData, "hex");

    const generator = new AtokRomajiSettingGenerator();
    generator.parseWindows(buffer);
    const result = generator.generateWindows().toString("hex");

    expect(result).toEqual(inputData);
});

test("Only add", () => {
    const generator = new AtokRomajiSettingGenerator();

    generator.add(",", "、");
    generator.add("-", "ー");
    generator.add(".", "。");
    generator.add("/", "・");
    generator.add("[", "「");
    generator.add("]", "」");
    generator.add("a", "あ");
    generator.add("ba", "ば");
    generator.add("be", "べ");
    generator.add("bi", "び");
    generator.add("bo", "ぼ");
    generator.add("bu", "ぶ");
    generator.add("bya", "びゃ");
    generator.add("bye", "びぇ");
    generator.add("byi", "びぃ");
    generator.add("byo", "びょ");
    generator.add("byu", "びゅ");
    generator.add("cha", "ちゃ");
    generator.add("che", "ちぇ");
    generator.add("chi", "ち");
    generator.add("cho", "ちょ");
    generator.add("chu", "ちゅ");
    generator.add("cya", "ちゃ");
    generator.add("cye", "ちぇ");
    generator.add("cyi", "ちぃ");
    generator.add("cyo", "ちょ");
    generator.add("cyu", "ちゅ");
    generator.add("da", "だ");
    generator.add("de", "で");
    generator.add("dha", "でゃ");
    generator.add("dhe", "でぇ");
    generator.add("dhi", "でぃ");
    generator.add("dho", "でょ");
    generator.add("dhu", "でゅ");
    generator.add("di", "ぢ");
    generator.add("do", "ど");
    generator.add("du", "づ");
    generator.add("dwu", "どぅ");
    generator.add("dya", "ぢゃ");
    generator.add("dye", "ぢぇ");
    generator.add("dyi", "ぢぃ");
    generator.add("dyo", "ぢょ");
    generator.add("dyu", "ぢゅ");
    generator.add("e", "え");
    generator.add("fa", "ふぁ");
    generator.add("fe", "ふぇ");
    generator.add("fi", "ふぃ");
    generator.add("fo", "ふぉ");
    generator.add("fu", "ふ");
    generator.add("fya", "ふゃ");
    generator.add("fye", "ふぇ");
    generator.add("fyi", "ふぃ");
    generator.add("fyo", "ふょ");
    generator.add("fyu", "ふゅ");
    generator.add("ga", "が");
    generator.add("ge", "げ");
    generator.add("gi", "ぎ");
    generator.add("go", "ご");
    generator.add("gu", "ぐ");
    generator.add("gwa", "ぐぁ");
    generator.add("gya", "ぎゃ");
    generator.add("gye", "ぎぇ");
    generator.add("gyi", "ぎぃ");
    generator.add("gyo", "ぎょ");
    generator.add("gyu", "ぎゅ");
    generator.add("ha", "は");
    generator.add("he", "へ");
    generator.add("hi", "ひ");
    generator.add("ho", "ほ");
    generator.add("hu", "ふ");
    generator.add("hya", "ひゃ");
    generator.add("hye", "ひぇ");
    generator.add("hyi", "ひぃ");
    generator.add("hyo", "ひょ");
    generator.add("hyu", "ひゅ");
    generator.add("i", "い");
    generator.add("ja", "じゃ");
    generator.add("je", "じぇ");
    generator.add("ji", "じ");
    generator.add("jo", "じょ");
    generator.add("ju", "じゅ");
    generator.add("jya", "じゃ");
    generator.add("jye", "じぇ");
    generator.add("jyi", "じぃ");
    generator.add("jyo", "じょ");
    generator.add("jyu", "じゅ");
    generator.add("ka", "か");
    generator.add("ke", "け");
    generator.add("ki", "き");
    generator.add("ko", "こ");
    generator.add("ku", "く");
    generator.add("kwa", "くぁ");
    generator.add("kya", "きゃ");
    generator.add("kye", "きぇ");
    generator.add("kyi", "きぃ");
    generator.add("kyo", "きょ");
    generator.add("kyu", "きゅ");
    generator.add("la", "ぁ");
    generator.add("le", "ぇ");
    generator.add("li", "ぃ");
    generator.add("lka", "ヵ");
    generator.add("lke", "ヶ");
    generator.add("lo", "ぉ");
    generator.add("ltsu", "っ");
    generator.add("ltu", "っ");
    generator.add("lu", "ぅ");
    generator.add("lwa", "ゎ");
    generator.add("lya", "ゃ");
    generator.add("lye", "ぇ");
    generator.add("lyi", "ぃ");
    generator.add("lyo", "ょ");
    generator.add("lyu", "ゅ");
    generator.add("ma", "ま");
    generator.add("me", "め");
    generator.add("mi", "み");
    generator.add("mo", "も");
    generator.add("mu", "む");
    generator.add("mya", "みゃ");
    generator.add("mye", "みぇ");
    generator.add("myi", "みぃ");
    generator.add("myo", "みょ");
    generator.add("myu", "みゅ");
    generator.add("n'", "ん");
    generator.add("na", "な");
    generator.add("ne", "ね");
    generator.add("ni", "に");
    generator.add("nn", "ん");
    generator.add("no", "の");
    generator.add("nu", "ぬ");
    generator.add("nya", "にゃ");
    generator.add("nye", "にぇ");
    generator.add("nyi", "にぃ");
    generator.add("nyo", "にょ");
    generator.add("nyu", "にゅ");
    generator.add("o", "お");
    generator.add("pa", "ぱ");
    generator.add("pe", "ぺ");
    generator.add("pi", "ぴ");
    generator.add("po", "ぽ");
    generator.add("pu", "ぷ");
    generator.add("pya", "ぴゃ");
    generator.add("pye", "ぴぇ");
    generator.add("pyi", "ぴぃ");
    generator.add("pyo", "ぴょ");
    generator.add("pyu", "ぴゅ");
    generator.add("ra", "ら");
    generator.add("re", "れ");
    generator.add("ri", "り");
    generator.add("ro", "ろ");
    generator.add("ru", "る");
    generator.add("rya", "りゃ");
    generator.add("rye", "りぇ");
    generator.add("ryi", "りぃ");
    generator.add("ryo", "りょ");
    generator.add("ryu", "りゅ");
    generator.add("sa", "さ");
    generator.add("se", "せ");
    generator.add("sha", "しゃ");
    generator.add("she", "しぇ");
    generator.add("shi", "し");
    generator.add("sho", "しょ");
    generator.add("shu", "しゅ");
    generator.add("si", "し");
    generator.add("so", "そ");
    generator.add("su", "す");
    generator.add("sya", "しゃ");
    generator.add("sye", "しぇ");
    generator.add("syi", "しぃ");
    generator.add("syo", "しょ");
    generator.add("syu", "しゅ");
    generator.add("ta", "た");
    generator.add("te", "て");
    generator.add("tha", "てゃ");
    generator.add("the", "てぇ");
    generator.add("thi", "てぃ");
    generator.add("tho", "てょ");
    generator.add("thu", "てゅ");
    generator.add("ti", "ち");
    generator.add("to", "と");
    generator.add("tsa", "つぁ");
    generator.add("tse", "つぇ");
    generator.add("tsi", "つぃ");
    generator.add("tso", "つぉ");
    generator.add("tsu", "つ");
    generator.add("tu", "つ");
    generator.add("twu", "とぅ");
    generator.add("tya", "ちゃ");
    generator.add("tye", "ちぇ");
    generator.add("tyi", "ちぃ");
    generator.add("tyo", "ちょ");
    generator.add("tyu", "ちゅ");
    generator.add("u", "う");
    generator.add("va", "う゛ぁ");
    generator.add("ve", "う゛ぇ");
    generator.add("vi", "う゛ぃ");
    generator.add("vo", "う゛ぉ");
    generator.add("vu", "う゛");
    generator.add("wa", "わ");
    generator.add("we", "うぇ");
    generator.add("wi", "うぃ");
    generator.add("wo", "を");
    generator.add("wu", "う");
    generator.add("wye", "ゑ");
    generator.add("wyi", "ゐ");
    generator.add("xa", "ぁ");
    generator.add("xe", "ぇ");
    generator.add("xi", "ぃ");
    generator.add("xka", "ヵ");
    generator.add("xke", "ヶ");
    generator.add("xo", "ぉ");
    generator.add("xtsu", "っ");
    generator.add("xtu", "っ");
    generator.add("xu", "ぅ");
    generator.add("xwa", "ゎ");
    generator.add("xya", "ゃ");
    generator.add("xye", "ぇ");
    generator.add("xyi", "ぃ");
    generator.add("xyo", "ょ");
    generator.add("xyu", "ゅ");
    generator.add("ya", "や");
    generator.add("ye", "いぇ");
    generator.add("yi", "い");
    generator.add("yo", "よ");
    generator.add("yu", "ゆ");
    generator.add("za", "ざ");
    generator.add("ze", "ぜ");
    generator.add("zi", "じ");
    generator.add("zo", "ぞ");
    generator.add("zu", "ず");
    generator.add("zya", "じゃ");
    generator.add("zye", "じぇ");
    generator.add("zyi", "じぃ");
    generator.add("zyo", "じょ");
    generator.add("zyu", "じゅ");

    for (const s of "bcdfghjklmnprstvwxyz") {
        generator.addSokuonCharacter(s);
    }

    generator.addHatsuonCharacter("n");

    const macosResult = generator.generateMacos().toString("base64");
    const macosSample = fs.readFileSync("./sample/sample_macos.txt", "ascii");
    expect(macosResult).toEqual(macosSample);

    const windowsResult = generator.generateWindows().toString("hex");
    const windowsSample = fs.readFileSync(
        "./sample/sample_windows.txt",
        "ascii",
    );
    expect(windowsResult).toEqual(windowsSample);
});
